[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "24"

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200
  force = true

[[redirects]]
  from = "/api/graphql"
  to = "/.netlify/functions/graphql"
  status = 200
  force = true
